# Generated by Django 4.0.4 on 2022-05-17 21:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monTiGMagasin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2022, 5, 17, 23, 10, 29, 344476)),
        ),
    ]
